name = "DiscreteEntropy"
uuid = "940648b6-1797-4129-9403-35667d1f6004"
authors = ["David Kelly <david.a.kelly@kcl.ac.uk> and contributors"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Changepoints = "98700a41-f20d-59c7-9e81-44d0470ae598"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
CSV = "0.10"
Changepoints = "0.4"
Distributions = "<0.25, 0.25"
Documenter = "0.27, 1"
Optim = "1.9"
QuadGK = "2.9.4"
Roots = "2.1.5"
SpecialFunctions = "1.8.1, 2"
Statistics = "1"
StatsBase = "<0.34.3, 0.34"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
